"""Build the browser catalogs from the reviewed JSON sources. Use --check in CI."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def build():
    catalogs = {name: json.loads((ROOT/'locales'/f'{name}.json').read_text()) for name in ('en', 'zh-CN')}
    assert catalogs['en'].keys() == catalogs['zh-CN'].keys(), 'Locale keys differ'
    for key, english in catalogs['en'].items():
        assert isinstance(english, str) and english, key
        assert set(re.findall(r'\{\w+\}', english)) == set(re.findall(r'\{\w+\}', catalogs['zh-CN'][key])), key
    server = json.loads((ROOT/'locales/server-keys.json').read_text())
    assert all(key in catalogs['en'] for key in server)
    return '// Generated by scripts/build_locales.py; edit locales/*.json.\nwindow.ORION_LOCALES = ' + json.dumps(catalogs, ensure_ascii=False, indent=2) + ';\nwindow.ORION_SERVER_KEYS = ' + json.dumps(server) + ';\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT/'web/locales.js'
    output = build()
    if args.check:
        if not path.exists() or path.read_text() != output:
            raise SystemExit('Regenerate catalogs: python scripts/build_locales.py')
        print('Locale keys, placeholders and generated asset match.')
    else:
        path.write_text(output)
